CREATE TABLE users(
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL,
gd DATE,
pwd VARCHAR(255),
created_at DATETIME NOT NULL DEFAULT CURRENT_TIME
);